name: CI

# Trigger this workflow on push or pull request
on: [push, pull_request]

env:
  SRC_DIR_PATH: desktop_version

jobs:
  build-mac:
    name: Build (macos-latest)

    runs-on: macos-latest

    env:
      CXXFLAGS: -I/usr/local/include/SDL2
      LDFLAGS: -L/usr/local/lib

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: brew install ninja sdl2 sdl2_mixer

    - name: CMake configure (default version)
      run: |
        mkdir ${SRC_DIR_PATH}/build && cd ${SRC_DIR_PATH}/build
        cmake -GNinja ..
    - name: Build (default version)
      run: ninja -C ${SRC_DIR_PATH}/build
    - name: Create Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: V6AP-macos
        path: ${{env.SRC_DIR_PATH}}/build/VVVVVV

  build-lin:
    name: Build (ubuntu-latest)

    runs-on: ubuntu-latest

    env:
      CXXFLAGS: -I/usr/local/include/SDL2
      LDFLAGS: -L/usr/local/lib

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install libsdl2-mixer-dev
      run: |
        sudo apt-get update -y
        sudo apt-get upgrade -y
        sudo apt-get install -y libsdl2-mixer-dev

    - name: CMake configure (default version)
      run: |
        mkdir ${SRC_DIR_PATH}/build && cd ${SRC_DIR_PATH}/build
        cmake ..
    - name: Build (default version)
      run: make -j $(nproc) -C ${SRC_DIR_PATH}/build
    - name: Create Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: V6AP-linux
        path: ${{env.SRC_DIR_PATH}}/build/VVVVVV

  build-win:
    name: Build (windows-latest)

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install dependencies (Windows)
      run: |
        vcpkg install sdl2 sdl2-mixer

    - name: CMake configure (default version)
      run: |
        mkdir $env:SRC_DIR_PATH/build
        cd $env:SRC_DIR_PATH/build
        $env:LDFLAGS =  "/LIBPATH:$env:VCPKG_INSTALLATION_ROOT\installed\x86-windows\lib "
        $env:LDFLAGS += "/LIBPATH:$env:VCPKG_INSTALLATION_ROOT\installed\x86-windows\lib\manual-link"
        cmake -G "Visual Studio 16 2019" -A Win32 `
              -DSDL2_INCLUDE_DIRS="$env:VCPKG_INSTALLATION_ROOT\installed\x86-windows\include\SDL2" `
              -DSDL2_LIBRARIES="SDL2;SDL2main;SDL2_mixer" `
              -DUSE_ZLIB=OFF `
              -DCMAKE_BUILD_TYPE=Release ..
    - name: Build (default version)
      run: |
        cd $env:SRC_DIR_PATH/build
        cmake --build . --config Release
    - name: Create Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: V6AP-win
        path: |
          ${{env.SRC_DIR_PATH}}/build/Release/VVVVVV.exe
          ${{env.SRC_DIR_PATH}}/build/bin/Release/APCpp.dll

